version: 2.0

jobs:
  bundle_dependencies:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/sample_app
    steps:
      - checkout
      - attach_workspace:
          at: ~/sample_app
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/sample_app/vendor/bundle
      - persist_to_workspace:
          root: .
          paths: vendor/bundle

  rake_test:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/sample_app
    steps:
      - checkout
      - attach_workspace:
          at: ~/sample_app
      - run: bundle --path vendor/bundle
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: bundle exec rake

  precompile_assets:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/sample_app
    steps:
      - checkout
      - attach_workspace:
          at: ~/sample_app
      - run: bundle --path vendor/bundle
      - run:
          name: Precompile assets
          command: bundle exec rake assets:precompile
      - persist_to_workspace:
          root: .
          paths: public/assets

  deploy:
    machine:
        enabled: true
    working_directory: ~/sample_app
    environment:
      - HEROKU_APP: safe-wildwood-45845
    steps:
      - checkout
      - attach_workspace:
          at: ~/sample_app
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh
      - run:
          command: |
            git push heroku workspace-forwarding:master
            heroku run rake db:migrate
            sleep 5 # sleep for 5 seconds to wait for dynos
            heroku restart

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - bundle_dependencies
      - rake_test:
          requires:
            - bundle_dependencies
      - precompile_assets:
          requires:
            - bundle_dependencies
      # - deploy:
      #     requires:
      #       - rake_test
      #       - precompile_assets